# Generated by Django 4.2.1 on 2025-06-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('siglas_autor_titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('clasificacion_cdu', models.CharField(blank=True, max_length=255, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
            ],
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multi', models.AutoField(primary_key=True, serialize=False)),
                ('profesor', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('carrera', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id_not', models.AutoField(primary_key=True, serialize=False)),
                ('marca_not', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('carrera', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id_proyector', models.AutoField(primary_key=True, serialize=False)),
                ('marca_pro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('varios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='materiales.varios')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='materiales.mapas')),
            ],
        ),
        migrations.CreateModel(
            name='EjemplarVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_varios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='materiales.tipovarios')),
            ],
        ),
        migrations.CreateModel(
            name='EjemplarProyector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=255)),
                ('proyector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='materiales.proyector')),
            ],
        ),
        migrations.CreateModel(
            name='EjemplarNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=255)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='materiales.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='EjemplarMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_registro', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='materiales.tipomapa')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ejemplar', models.IntegerField()),
                ('sede', models.CharField(max_length=255)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='materiales.libro')),
            ],
        ),
    ]
