# Generated by Django 4.2.11 on 2024-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_libro_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen_rota',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_rota/'),
        ),
    ]
