# Generated by Django 5.0.7 on 2024-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_inventario_imagen_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(default='Disponible', max_length=255, null=True),
        ),
    ]
