# Generated by Django 5.2.3 on 2025-06-26 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Disponible', max_length=255, null=True)),
                ('motivo_baja', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('num_ejemplar', models.IntegerField(null=True)),
                ('imagen_rota', models.ImageField(blank=True, null=True, upload_to='imagenes_rota/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos.', regex='^\\d{7,8}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perfil', models.CharField(choices=[('alumno', 'Alumno'), ('bibliotecaria', 'Bibliotecaria')], default='alumno', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuarios_custom', related_query_name='usuario_custom', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_custom', related_query_name='usuario_custom', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('clasificacion_cdu', models.CharField(default='Sin clasificar', max_length=255)),
                ('siglas_autor_titulo', models.CharField(default='ABC', max_length=255)),
                ('num_inventario', models.IntegerField(default=1)),
                ('resumen', models.TextField()),
                ('etiqueta_palabra_clave', models.TextField(default='Roma,Historia,Clasica')),
                ('sede', models.TextField(default='La Plata')),
                ('disponibilidad', models.CharField(default='Disponible', max_length=255, null=True)),
                ('observaciones', models.TextField(default='Esta es una observación')),
                ('img', models.URLField()),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_mapa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_multi', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=255)),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_not', models.AutoField(primary_key=True, serialize=False)),
                ('marca_not', models.CharField(max_length=255)),
                ('modelo_not', models.CharField(max_length=255)),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_proyector', models.AutoField(primary_key=True, serialize=False)),
                ('marca_pro', models.CharField(max_length=255)),
                ('modelo_pro', models.CharField(max_length=255)),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_varios', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            bases=('materiales.inventario',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_reserva', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Reserva Solicitada'), ('aprobado_reserva', 'Reserva Aprobada'), ('aprobado', 'Préstamo Activo'), ('rechazado', 'Reserva Rechazada'), ('finalizado', 'Finalizado'), ('vencido', 'Vencido')], default='solicitado', max_length=20)),
                ('tipo_prestamo', models.CharField(choices=[('domicilio', 'Préstamo a Domicilio'), ('aula', 'Préstamo en Aula')], default='domicilio', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], default='alumno', max_length=10)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_retiro_real', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_usuario', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='materiales.libro')),
            ],
        ),
    ]
