# Generated by Django 5.2.3 on 2025-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='img',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
