# Generated by Django 5.2.3 on 2025-07-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_libro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='resumen',
        ),
    ]
