# Generated by Django 5.2.3 on 2025-07-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_libro_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='num_inventario',
        ),
    ]
