# Generated by Django 5.2.3 on 2025-07-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_remove_libro_num_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='contenido',
            new_name='titulo_contenido',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='marca_not',
        ),
        migrations.AddField(
            model_name='mapas',
            name='denominacion',
            field=models.TextField(default='Completar'),
        ),
        migrations.AddField(
            model_name='mapas',
            name='num_registro',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='mapas',
            name='sede',
            field=models.TextField(default='La Plata'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='carrera',
            field=models.TextField(default='Carrera'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='ingresar_enlace',
            field=models.URLField(blank=True, help_text='Ingrese la URL del contenido multimedia', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='profesor',
            field=models.TextField(default='Profesor/a'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='num_registro',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='notebook',
            name='sede',
            field=models.TextField(default='La Plata'),
        ),
    ]
