# Generated by Django 5.2.3 on 2025-07-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_rename_contenido_multimedia_titulo_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyector',
            name='marca_pro',
        ),
        migrations.AddField(
            model_name='proyector',
            name='num_registro',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='proyector',
            name='sede',
            field=models.TextField(default='La Plata'),
        ),
    ]
