# Generated by Django 5.2.3 on 2025-08-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_remove_proyector_marca_pro_proyector_num_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='materiales.inventario')),
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('profesor', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=255)),
                ('ingresar_enlace', models.URLField(blank=True, help_text='Ingrese la URL del programa', max_length=500, null=True)),
                ('ciclo_lectivo', models.CharField(default='2024', max_length=4)),
                ('sede', models.CharField(default='La Plata', max_length=255)),
                ('disponibilidad', models.CharField(default='Disponible', max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, default='', max_length=500, null=True)),
            ],
            bases=('materiales.inventario',),
        ),
    ]
