# Generated by Django 5.0.6 on 2025-09-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='marca',
            field=models.CharField(default='Sin especificar', max_length=255),
        ),
        migrations.AddField(
            model_name='notebook',
            name='num_serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
