# Generated by Django 5.0.6 on 2025-09-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0008_notebook_marca_notebook_num_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='num_serie',
        ),
    ]
