# Generated by Django 5.2.4 on 2025-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_remove_notebook_num_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='clasificacion_cdu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='siglas_autor_titulo',
            field=models.CharField(max_length=255),
        ),
    ]
