# Generated by Django 5.2.4 on 2025-10-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0010_alter_libro_clasificacion_cdu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='ciclo_lectivo',
            field=models.CharField(max_length=4),
        ),
    ]
