# Generated by Django 5.2.4 on 2025-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0011_alter_programa_ciclo_lectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='num_registro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='sede',
            field=models.TextField(),
        ),
    ]
