# Generated by Django 5.0.6 on 2025-10-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0012_alter_notebook_num_registro_alter_notebook_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='varios',
            name='sede',
            field=models.CharField(default='La Plata', max_length=255),
        ),
    ]
