# Generated by Django 5.0.6 on 2025-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0013_varios_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='sede',
            field=models.CharField(default='La Plata', max_length=255),
        ),
    ]
