# Generated by Django 5.0.6 on 2025-10-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0014_multimedia_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='sede',
            field=models.TextField(default='La Plata'),
        ),
    ]
