# Generated by Django 4.2.23 on 2025-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0015_alter_multimedia_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='varios',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad total de este tipo de material'),
        ),
        migrations.AddField(
            model_name='varios',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad disponible para préstamo'),
        ),
    ]
