# Generated by Django 4.2.23 on 2025-10-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0016_varios_cantidad_varios_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='marca',
        ),
    ]
