# Generated by Django 4.2.23 on 2025-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0017_remove_notebook_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('bibliotecaria', 'Bibliotecaria'), ('docente', 'Docente')], default='alumno', max_length=20),
        ),
    ]
