# Generated by Django 5.2.4 on 2025-10-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0018_alter_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='sede',
        ),
    ]
