# Generated by Django 4.2.23 on 2025-10-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0019_remove_multimedia_sede_remove_programa_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('bibliotecaria', 'Bibliotecaria'), ('docente', 'Docente')], default='estudiante', max_length=20),
        ),
    ]
