# Generated by Django 4.2.23 on 2025-10-27 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0021_update_existing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sancion', models.CharField(choices=[('inhabilitacion_mesas', 'Inhabilitación para Mesas de Final'), ('suspension_prestamos', 'Suspensión de Préstamos')], default='inhabilitacion_mesas', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('cumplida', 'Cumplida/Finalizada')], default='pendiente', max_length=15)),
                ('tipo_usuario_sancion', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente')], default='estudiante', help_text='Tipo de usuario al que se aplica la sanción', max_length=10)),
                ('fecha_suspension_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta la que está suspendido el docente (3 meses)', null=True)),
                ('acumulado_sanciones', models.IntegerField(default=0, help_text='Número de sanciones acumuladas del docente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(default='Préstamo vencido')),
                ('observaciones_bibliotecaria', models.TextField(blank=True, null=True)),
                ('libro_devuelto_catalogo', models.BooleanField(default=False)),
                ('fecha_devolucion_catalogo', models.DateTimeField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='materiales.prestamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
