# Generated by Django 5.0.6 on 2025-10-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0022_sancion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sancion',
        ),
    ]
