# Generated by Django 4.2.23 on 2025-10-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0023_delete_sancion'),
    ]

    operations = [
        # Removed problematic AlterField operation for inventario_ptr
        # This was causing SQLite AUTOINCREMENT syntax errors
    ]
