# Generated by Django 4.2.23 on 2025-10-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0023_delete_sancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='inventario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materiales.inventario'),
        ),
    ]
