# Generated by Django 4.2.23 on 2025-10-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0024_alter_multimedia_inventario_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapas',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varios',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),

    ]
