# Generated by Django 4.2.23 on 2025-11-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0025_libro_fecha_baja_mapas_fecha_baja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='img',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='observaciones',
        ),
    ]
