# Generated by Django 4.2.23 on 2025-11-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0026_remove_observaciones_img_from_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='disponibilidad',
        ),
    ]
