# Generated by Django 4.2.23 on 2025-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0027_remove_programa_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyector',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
