# Generated by Django 4.2.2 on 2025-06-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Reserva Solicitada'), ('aprobado_reserva', 'Reserva Aprobada'), ('aprobado', 'Préstamo Activo'), ('rechazado', 'Reserva Rechazada'), ('finalizado', 'Finalizado'), ('vencido', 'Vencido')], default='solicitado', max_length=20),
        ),
    ]
