# Generated by Django 4.2.11 on 2024-09-19 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
                ('motivo_baja', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('num_ejemplar', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_libro', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('cdu', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('img', models.URLField()),
            ],
            bases=('libros.inventario',),
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_mapa', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            bases=('libros.inventario',),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_multi', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=255)),
            ],
            bases=('libros.inventario',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_not', models.IntegerField(primary_key=True, serialize=False)),
                ('marca_not', models.CharField(max_length=255)),
                ('modelo_not', models.CharField(max_length=255)),
            ],
            bases=('libros.inventario',),
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_proyector', models.IntegerField(primary_key=True, serialize=False)),
                ('marca_pro', models.CharField(max_length=255)),
                ('modelo_pro', models.CharField(max_length=255)),
            ],
            bases=('libros.inventario',),
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='libros.inventario')),
                ('id_varios', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            bases=('libros.inventario',),
        ),
    ]
