# Generated by Django 5.0.7 on 2025-08-13 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_prestamo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sancion', models.CharField(choices=[('inhabilitacion_mesas', 'Inhabilitación para Mesas de Final'), ('suspension_prestamos', 'Suspensión de Préstamos')], default='inhabilitacion_mesas', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('cumplida', 'Cumplida/Finalizada')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(default='Préstamo vencido')),
                ('observaciones_bibliotecaria', models.TextField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='libros.prestamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
