# Generated by Django 4.2.11 on 2024-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_inventario_delete_autor_delete_libros_libro_mapas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='cdu',
        ),
        migrations.AddField(
            model_name='libro',
            name='codigo_materia',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='num_inventario',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='siglas_autor_titulo',
            field=models.CharField(default='ABC', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_inventario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='motivo_baja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='num_ejemplar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
