# Generated by Django 5.2.3 on 2025-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancion',
            name='fecha_devolucion_catalogo',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el libro fue devuelto al catálogo', null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='libro_devuelto_catalogo',
            field=models.BooleanField(default=False, help_text='Indica si el libro fue devuelto al catálogo tras cancelar la sanción'),
        ),
    ]
