# Generated by Django 4.2.6 on 2024-09-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_remove_libro_cdu_libro_codigo_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.IntegerField(default=1999),
        ),
    ]
