# Generated by Django 5.2.3 on 2025-08-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_sancion_fecha_devolucion_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancion',
            name='acumulado_sanciones',
            field=models.IntegerField(default=0, help_text='Número de sanciones acumuladas del docente'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='fecha_suspension_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la que está suspendido el docente (3 meses)', null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='tipo_usuario_sancion',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente')], default='alumno', help_text='Tipo de usuario al que se aplica la sanción', max_length=10),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='fecha_devolucion_catalogo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='libro_devuelto_catalogo',
            field=models.BooleanField(default=False),
        ),
    ]
