# Generated by Django 5.2.3 on 2025-08-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_sancion_acumulado_sanciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('bibliotecaria', 'Bibliotecaria'), ('profesor', 'Profesor')], default='alumno', max_length=20),
        ),
    ]
