# Generated by Django 5.2.3 on 2025-08-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('bibliotecaria', 'Bibliotecaria'), ('docente', 'Docente')], default='alumno', max_length=20),
        ),
    ]
