# Generated by Django 5.0.6 on 2024-10-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapas',
            name='id_mapa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='id_multi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='id_not',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyector',
            name='id_proyector',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varios',
            name='id_varios',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
