# Generated by Django 4.2.1 on 2025-04-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_alter_mapas_id_mapa_alter_multimedia_id_multi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Reserva Solicitada'), ('aprobado', 'Préstamo Activo'), ('rechazado', 'Reserva Rechazada'), ('finalizado', 'Finalizado')], default='solicitado', max_length=20)),
                ('tipo_prestamo', models.CharField(choices=[('domicilio', 'Préstamo a Domicilio'), ('aula', 'Préstamo en Aula')], default='domicilio', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], default='alumno', max_length=10)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='libros.libro')),
            ],
        ),
    ]
