# Generated by Django 5.2.3 on 2025-08-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='extension_solicitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_extension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='motivo_extension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
