# Generated by Django 5.2.3 on 2025-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_prestamo_extension_solicitada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
