# Generated by Django 4.2.2 on 2025-05-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_limite_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Reserva Solicitada'), ('aprobado', 'Préstamo Activo'), ('rechazado', 'Reserva Rechazada'), ('finalizado', 'Finalizado'), ('vencido', 'Vencido')], default='solicitado', max_length=20),
        ),
    ]
