# Generated by Django 5.2.3 on 2025-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_alter_libro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='imagen_rota',
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen_rota_contenido',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen_rota_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen_rota_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
