# Generated by Django 4.2.2 on 2025-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_prestamo_fecha_limite_reserva_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_retiro_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
